// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZLoLrfmPOY4RkN8J49qekF80SITtum80',
    appId: '1:152020128383:web:70667d89aa21dfe533254a',
    messagingSenderId: '152020128383',
    projectId: 'grocery-app-72',
    authDomain: 'grocery-app-72.firebaseapp.com',
    storageBucket: 'grocery-app-72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2WOyfqcxQ4BPkP5oBJQqFUtZ5oeDsgk',
    appId: '1:152020128383:android:464a4d1c1fc5454933254a',
    messagingSenderId: '152020128383',
    projectId: 'grocery-app-72',
    storageBucket: 'grocery-app-72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-Sns7xKhrqTmTpWcUkZuYWCD07WJRwU',
    appId: '1:152020128383:ios:42e52f572b3b6afd33254a',
    messagingSenderId: '152020128383',
    projectId: 'grocery-app-72',
    storageBucket: 'grocery-app-72.appspot.com',
    iosClientId: '152020128383-5fuqbl3cmlidkim4026fd07st2519god.apps.googleusercontent.com',
    iosBundleId: 'me.dhruvcodes.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-Sns7xKhrqTmTpWcUkZuYWCD07WJRwU',
    appId: '1:152020128383:ios:42e52f572b3b6afd33254a',
    messagingSenderId: '152020128383',
    projectId: 'grocery-app-72',
    storageBucket: 'grocery-app-72.appspot.com',
    iosClientId: '152020128383-5fuqbl3cmlidkim4026fd07st2519god.apps.googleusercontent.com',
    iosBundleId: 'me.dhruvcodes.grocery',
  );
}
